[build]
  command = "npm run build"
  publish = "dist/JICHO-LANDING-PAGE/browser"

[functions]
  directory = "dist/JICHO-LANDING-PAGE/server"

[[plugins]]
  package = "@netlify/plugin-angular"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200