[build]
  command   = "npm run build"               # or your SSR build script
  publish   = "dist/JICHO-LANDING-PAGE"     # ← point here, plugin adds /browser
  functions = "dist/JICHO-LANDING-PAGE/server"

[[plugins]]
  package   = "@netlify/angular-runtime"
