[build]
  command   = "npm run build"            # or your SSR script
  publish   = "dist/JICHO-LANDING-PAGE"  # plugin adds /browser
  functions = "dist/JICHO-LANDING-PAGE/server"

[[plugins]]
  package = "@netlify/angular-runtime"
