[build]
  command   = "npm run build"
  publish   = "dist/JICHO-LANDING-PAGE"         # plugin will append /browser
  functions = "dist/JICHO-LANDING-PAGE/server"



[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
